---

- name: Install docker
  hosts: docker_server
  become: yes
  tasks:
    - name: install docker
      yum:
        name: docker
        update_cache: yes
        state: present

- name: Start docker
  hosts: docker_server
  become: yes
  tasks:
    - name: start docker
      systemd:
        name: docker
        state: started      